apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: backend-sockets
    name: backend-sockets
spec:
    replicas: 2
    selector:
        matchLabels:
            app: backend-sockets
    template:
        metadata:
            labels:
                app: backend-sockets
        spec:
            containers:
            - image: alexbaily/sockets:latest
              imagePullPolicy: Always
              name: backend-sockets
              ports:
                - containerPort: 8080

